name: spring-boot-mvc-intro continuous check

on: 
  push:
    paths:
      - code/jvm/spring-boot-mvc-intro/**

jobs:
  build:
    name: spring-boot-mvc-intro Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        run: ./code/jvm/spring-boot-mvc-intro/gradlew -p code/jvm/spring-boot-mvc-intro check --info
  