name: spring-servlets continuous check

on: 
  push:
    paths:
      - code/jvm/servlets/**

jobs:
  build:
    name: Servlets Example Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        run: ./code/jvm/servlets/gradlew -p code/jvm/servlets check --info
  